version: "3"

services:
  vue-rabbitmq:
    build: .
    container_name: vue-rabbit
    command: "npm run serve"
    volumes:
      - ./rabbitmq-queue-design:/usr/app
    ports:
      - 8000:8080        