version: "3"

services:
  vue-rabbitmq:
    build: .
    container_name: vue-rabbit
    command: "npm run serve"
    volumes:
      - ./rabbitmq-queue-design:/usr/app
    ports:
      - 8000:8080        
  rabbitmq-server:
    image: rabbitmq:latest
    container_name: rabbitmq_andrei
    hostname: andrei_host
    ports:
      - "5671:5672"     